const mockedCalendar = [
  {
    id: 1,
    title: 'Evento Test',
    description: 'Descirpcion de evento test',
    day: 1,
    month: 4,
    year: 2023,
    location: 'Av. Libertador 4000',
    startTime: '20:00',
    endTime: '22:00',
    link: 'https://www.capbadistrito2.com',
  },
  {
    id: 2,
    title: 'Evento Test 2',
    description: 'Descripcion de evento test 2',
    day: 2,
    month: 5,
    year: 2023,
    location: 'Av del Cano, Ramos Mejia',
    startTime: '19:00',
    endTime: '20:00',
    link: 'https://www.capbadistrito2.com',
  },
  {
    id: 2,
    title: 'Evento Test 4',
    description:
      'Descripcion de evento test que se realizara en algun lugar de la provincia de Buenos Aires',
    day: 17,
    month: 5,
    year: 2023,
    location: 'Av del Cano, Ramos Mejia',
    startTime: '19:00',
    endTime: '20:00',
    link: 'https://www.capbadistrito2.com',
  },
  {
    id: 3,
    title: 'Evento Test 3',
    description: 'Descripcion de evento test 3',
    day: 23,
    month: 7,
    year: 2023,
    location: 'Libertad 548, AMBA',
    startTime: '09:00',
    endTime: '10:00',
    link: 'https://www.capbadistrito2.com',
  },
];

export default mockedCalendar;
